### ISSUE TITLE
Support "max" on days field in coins.getCoinMarketChart (coins/{id}/market_chart

### ISSUE THREAD

**Issue by georgeherby** [yegor-pelykh/coingecko_api#3]
Example url -> https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=gbp&days=max

Current the code only allows int but needs to allow the string of "max"

![Screenshot 2022-01-30 at 18 48 00](https://user-images.githubusercontent.com/21989833/151713146-74c01f45-7215-4458-9155-5d7319191719.png)

**Comment by yegor-pelykh** [comment]
Hi @georgeherby
You're right. In general, this is relevant to three methods: `getCoinMarketChart`, `getCoinOHLC`, `getContractMarketChart`. They should all have the same ability to specify a maximum number of days.
Now, if the "days" parameter is not specified in these methods, the maximum possible number of days is assumed.
This has been fixed in release 1.0.2, which has just been published. 

Thank you for your interest in improving this package!
